require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

# Exlucdeに設定したファイルはチェックの対象外になります。
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'tmp/**/*'

Rails:
  Enabled: true

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# app/controllers以下のメソッドのprefixに「set_」「get_」を許可
Naming/AccessorMethodName:
  Exclude:
    - "app/controllers/**/*"

# クラスにコメントを残すのを許可
Style/Documentation:
  Enabled: false

# RSpecのsystemテストにおけるexpectの数制限を解除
RSpec/MultipleExpectations:
  Enabled: false

# RSpecの1つ辺りのテストコード行制限を解除
RSpec/ExampleLength:
  Enabled: false

# RspecのsystemテストでHTTP Status CodeよりSymbolを優先する規約を解除(Codeの方が共有しやすいとの判断から)
RSpec/Rails/HttpStatus:
  Enabled: false

# 以下、初期状態でRubocopに引っかかる項目をスキップさせています。
# 初期設定で引っかかっている項目
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/*'

Rails/FilePath:
  Exclude:
    - 'config/environments/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SymbolArray:
  Exclude:
    - 'config/initializers/filter_parameter_logging.rb'

Layout/CommentIndentation:
  Exclude:
    - 'config/environments/development.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/sorcery.rb'

RSpec/ContextWording:
  Enabled: false

# rescue の 'e' 変数を他のメソッドに渡す際、引数の文字数は3文字以上の必要がありますが、
# 'e'を変えると、rescue内容を格納する変数は'e'を使用するようにと指摘されてしまうため、
# 現状は限定的に該当のファイルのみ3文字以上の制約を解除しています。
Naming/MethodParameterName:
  Exclude:
    - 'app/models/scheduler.rb'
